apiVersion: v1
description: A Slack bot for Jenkins X
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-website/master/images/logo/jenkinsx-icon-color.svg
home: https://github.com/jenkins-x-plugins/jx-slack
name: jx-slack
version: 0.1.1
appVersion: 0.1.1
sources:
  - https://github.com/jenkins-x-plugins/jx-slack
