{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-23T17:25:10Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      fix: use nicer PR message
    sha: 3f2bacac6319541bdb48d51e29bee707580af929
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      fix: lint the code a bit more
    sha: 829627a4095ea9f1bb3b3e2852f9508f99f81151
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      chore: fmt
    sha: d7a74bb54edd575f6a1a8b4b5bf4793da12a6a16
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      fix: use nicer annotation for message ids
    sha: 51b6f088a2b127fa67be7b39dd15244821f923be
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      fix: add context to message
    sha: f18ec0ed84ab306f8ab030592223b61ed0ee420b
  gitHttpUrl: https://github.com/jenkins-x-plugins/jx-slack
  gitOwner: jenkins-x-plugins
  gitRepository: jx-slack
  name: '{{ .Chart.Name }}'
  version: 0.0.54
status: {}
 
{{- end }}
