{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-22T08:36:15Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      chore: fix chart
    sha: adcc0c4aa398ea2698edec7652aa64c739d9bec9
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      chore: fix labels
    sha: cf9e634c9fe369b7ad819ba81986fe9e031bbc04
  gitHttpUrl: https://github.com/jenkins-x-plugins/jx-slack
  gitOwner: jenkins-x-plugins
  gitRepository: jx-slack
  name: '{{ .Chart.Name }}'
  version: 0.0.44
status: {}
 
{{- end }}
