{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-22T09:59:58Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      fix: polish logging
    sha: de0e991bd8e4c8f828dcc28d589a23e80e3dcbfd
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      fix: allow patch updates of PAs
    sha: 239dcc65bc1e5aed4d997bd8e253ceb96ef1375e
  gitHttpUrl: https://github.com/jenkins-x-plugins/jx-slack
  gitOwner: jenkins-x-plugins
  gitRepository: jx-slack
  name: '{{ .Chart.Name }}'
  version: 0.0.51
status: {}
 
{{- end }}
